### ISSUE TITLE
Inconsistency in modeling results across sitar versions

### ISSUE THREAD

**Issue by corinne-riddell** [statist7/sitar#2]
I've been using sitar version 1.0.3 on R version 3.1.3. I recently updated sitar to version 1.0.7 and R to version 3.2.4 and re-ran some of my earlier models but found that the results had changed. The difference in results can be re-created using the heights dataset:

```
# running R version 3.1.3 and sitar 1.0.3
library(sitar)
data(heights)

mod103 <- sitar(age, height, id, heights, 3, random="c")

#print out variance explained, AIC, and BIC to compare to other version:
varexp(mod103)
mod103 
 78.09 

AICadj(mod103)
mod103 
 662 

BICadj(mod103)
mod103 
 681.8 

###################################################
# running R version 3.2.4 and sitar 1.0.7
library(sitar)
data(heights)

mod107 <- sitar(age, height, id, heights, 3, random="c")

#print out variance explained, AIC, and BIC to compare to other version:
varexp(mod107)
mod107 
 32.65

AICadj(mod107)
mod107
 779.6 

BICadj(mod107)
mod107
799.3
```

So far, I've found that models including random effects for "a" and "b" alone to be equivalent, but there seems to be quite a difference in the above model when only including a random effect for "c" (especially in terms of the variance explained). 

I see in the help notes that models fitted prior to 1.0.5 need refitting, but given this large difference in the variance explained, I was wondering which of these model fits is the appropriate one? Apologies if I missing something in the documentation that explains this!

**Comment by statist7** [comment]
Hi Corinne, thanks for your report.

My first thought is that your model is very odd, with a random effect for c but not a, i.e. a random slope but no random intercept.

But that said, I think the discrepancy arises because the default for xoffset has changed from 1.0.3 to 1.0.7. Because you don't have a random intercept the same intercept is used for all subjects, which will materially affect the slopes if it changes. You can experiment with different values of xoffset and you'll see that the results are very sensitive to the value chosen.

My advice to you would be to include a random effect for a when you fit one for c. This makes the results much less sensitive to the  value of xoffset. However it does still make a bit of difference, which unfortunately is inevitable because of the way the sitar model is defined - it is not invariant to the choice of age origin.

**Comment by statist7** [comment]
Sorry, I didn't mean to close the issue before hearing your response. But I don't see it as a software issue.

**Comment by corinne-riddell** [comment]
Hi Tim,

Thank you for your speedy reply and this clarification -- this helps me a lot to conceptualize the models. With what you've said in mind, I can get the same results as mod103 if I add xoffset = 0 in the statement for mod107. 

I agree that this model by itself seems odd. As background, I've been running a series of models, with 1, 2, and 3 random effects to see how this affects model fit and as part of an algorithm to choose the model with the best fit. 

Is the purpose of defaulting xoffset = mean(x) to reduce the possibility of the model not converging, or is there another conceptual reason why we'd want mean(x) to be the default (at least in some substantive contexts)? I'm trying to decide what makes the most sense for my situation. At least with the simple, albeit odd, model shown above, I think the default to mean(x) actually forces a fit that doesn't seem natural for the context -- for all the girls to have the same estimated height at the mean age. Best captured by plotting the individual fitted trajectories: 

`plot.sitar(mod103, opt = "D")`
![image](https://cloud.githubusercontent.com/assets/12090129/17973810/d80269e4-6ab1-11e6-873f-34af5ccb2ea3.png)

vs. 
`plot(mod107, opt = "D")`
![image](https://cloud.githubusercontent.com/assets/12090129/17973853/f17fffe4-6ab1-11e6-9a93-bd35cc4f9cbb.png)

Because of this, my inclination would be to set xoffset=0 in my models, but it would be good for me to know if you advise against this.

**Comment by statist7** [comment]
There is no absolute reason why xoffset defaults to mean(x), but it is commonly recommended that covariates be centred before analysis, and this is what the default does. If you find that xoffset = 0 gives better results then you should use it - that's why I provide it as an argument. I wish I could provide some simple guidelines about the choice of xoffset, but the best I can do is to encourage you to experiment!

Your graph for mod103 is slightly misleading - the curves all look sensible because they are constrained to pass through the same intercept. The plot for mod107 looks odd but is actually a better representation of the c random effect model - the curve slopes differ far more with mod107 than they do with mod103 because the mod107 intercept coincides with the mean, so the slopes are not constrained in the way they are with mod103.

**Comment by corinne-riddell** [comment]
This makes sense, I'll re-run my best-fitting models with age centred to understand how this affects the model fit. Thanks for the discussion!
