### ISSUE TITLE
Error while running on a clean dataset

### ISSUE THREAD

**Issue by koundy** [statist7/sitar#4]
I am trying to build a sitar model and getting the following error with the dataset which has no NA and negative values. 

Error in diff[pp != 0] <- pp[pp != 0] * ssize : 
  NAs are not allowed in subscripted assignments

**Comment by statist7** [comment]
The sitar code does not include a variable called pp, so the problem must be in a calling function.

To investigate this I suggest you send me a reproducible example or reprex - the reprex package is useful here.

Best wishes,
Tim

**Comment by koundy** [comment]
Hi Tim,

Thanks for the reply. As I understand, the error is from the nlme package But I am unable to troubleshoot. Shall I mail you the sample dataset I am working with and sample code? 

Thanks,
Koundi

**Comment by statist7** [comment]
Yes do

Best wishes,
Tim

Sent from my iPhone

On 30 Mar 2019, at 11:48, Koundinya Desiraju <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Tim,

Thanks for the reply. As I understand, the error is from the nlme package But I am unable to troubleshoot. Shall I mail you the sample dataset I am working with and sample code?

Thanks,
Koundi

**Comment by statist7** [comment]
Your code

`model1 <- sitar(x = x, y = y, data = sample_dat, id = id, knots = 3, random = 'a')`

is odd in two respects - it specifies a knot at age 3 (outside the age range, so it fails) and the random effect `a` but not the random effects `b` or `c`. Maybe you meant `df` rather than `knots`. 

`sitar` now checks that the knots are within range.
